In [1]:
import numpy as np

In [ ]:
# !pip install numpy 
#

In [2]:
a = np.array([8,6,5])

In [10]:
k= np.array([[3,8,4], [9,3,5], [11,15,17], [19,31,8]])
print(k)

[[ 3  8  4]
 [ 9  3  5]
 [11 15 17]
 [19 31  8]]


In [11]:
k.shape

(4, 3)

In [14]:
m=np.array([[[4,41],[8,81],[7,71]],
            [[3,31],[1,11],[5,51]],
            [[6,61],[9,91],[13,131]]])
# print(m)
m.shape

(3, 3, 2)

In [ ]:
# There are mainly three ways to talk to an element in an array 
# indexing --> k[1][0]
# scrpting --> k[1,0] -->
# slicing --> ek range pakas kar nikalna --> k[1,0:3] --> k[row, from start: to end : kaise jana hai] or k[1,0:3:1]
# example --> k[first dimension, second dimesion, third dimension]
# 


In [30]:
# k[1][0]
# k[1,0]
# k[0:5:1, 2] or k[:,2]




()

In [27]:
# m[1, 1, 0]
# m[1, 1, 0:2]


array([], shape=(0, 2), dtype=int32)

In [31]:
# In python there if we do indexing form left side than it is positive 0,1,2,..and so on
# and if we do indexing from left side than we it negative indexing -1, -2, -3...and so on 

# When we do slicing do slice on every one, if we donnot do on every than shape bigad jata hai


In [34]:
# Always do slicing on every index

# k[:,2]
k[:, 2:3]

array([[ 4],
       [ 5],
       [17],
       [ 8]])

In [42]:
# m[1:3, 1:3, 0:1] # here we do slicing in every element because of maintain the shape 
# m[1:, 1:, :1] 


m[1:3, 0:1, 0:2]

array([[[ 3, 31]],

       [[ 6, 61]]])

In [45]:
x = [3,5,9]
x+5

# in list we can not add 


TypeError: can only concatenate list (not "int") to list

In [47]:
# Scalar addition is possible in array
# k+5
# k*3




array([[ 9, 24, 12],
       [27,  9, 15],
       [33, 45, 51],
       [57, 93, 24]])

In [48]:
a[0]

8

In [54]:
# a
a[0] = 13
a


# array is a kind of mutable collection where is can change the array 

array([13,  6,  5])

In [55]:
k

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [71]:
k[0,:] = [30,40,50]
k
# k.shape


array([[ 30,  40,  50],
       [  9,  30,   5],
       [ 11, 150,  17],
       [ 19, 310,   8]])

In [72]:
# k[0:4, 1] = [401,301, 151, 311]
k[:, 1] = [401,301, 151, 311]
k
# k.shape

array([[ 30, 401,  50],
       [  9, 301,   5],
       [ 11, 151,  17],
       [ 19, 311,   8]])

In [77]:
# k[0:2, 1:3,] = [[202,303],[404,505]]
k[:2, 1:] = [[202,303],[404,505]]
k

array([[ 30, 202, 303],
       [  9, 404, 505],
       [ 11, 151,  17],
       [ 19, 311,   8]])

In [79]:
k[4,:] = [1,1,1]
k

IndexError: index 4 is out of bounds for axis 0 with size 4

In [95]:
# To add a row in existing array we use a function append  

np.append(k,[[1,1,1]],axis=0) # zero to add row-wise

array([[ 30, 202, 303],
       [  9, 404, 505],
       [ 11, 151,  17],
       [ 19, 311,   8],
       [  1,   1,   1]])

In [97]:
k # it does not change 

array([[ 30, 202, 303],
       [  9, 404, 505],
       [ 11, 151,  17],
       [ 19, 311,   8]])

In [99]:
np.append(k,[[2],[2],[2],[2]],axis=1) # it only append column in array it not update the original array 


array([[ 30, 202, 303,   2],
       [  9, 404, 505,   2],
       [ 11, 151,  17,   2],
       [ 19, 311,   8,   2]])

In [101]:
k

array([[ 30, 202, 303],
       [  9, 404, 505],
       [ 11, 151,  17],
       [ 19, 311,   8]])

In [108]:
# To Delete row
# np.delete(k,1,0)
np.delete(k,0,axis=0)

array([[  9, 404, 505],
       [ 11, 151,  17],
       [ 19, 311,   8]])

In [107]:
# To delete the Column
# np.delete(k,1,1)
np.delete(k,0,axis=1)

array([[202, 303],
       [404, 505],
       [151,  17],
       [311,   8]])

In [109]:
k.size

12

In [110]:
k.reshape(6,2) # it only give the result it does not update the original k


array([[ 30, 202],
       [303,   9],
       [404, 505],
       [ 11, 151],
       [ 17,  19],
       [311,   8]])

In [113]:
# it chnage and update also
k.reshape(6,2) 

array([[ 30, 202],
       [303,   9],
       [404, 505],
       [ 11, 151],
       [ 17,  19],
       [311,   8]])

In [116]:
a1 = np.array([3.5,3,7])
a1

# Array is a homogenious function and in this float has highest priority that why it change all in float type

array([3.5, 3. , 7. ])

In [115]:
a1.dtype

dtype('float64')

In [118]:
a1.astype('uint16')

array([3, 3, 7], dtype=uint16)

In [119]:
# More function 
# a1.sum()
# a1.mean()


In [121]:
k.std(axis=1)

array([112.70117815, 214.02024826,  64.62885492, 140.31472561])

In [125]:
# np.arange(1,11,1) # it is another version w
# np.linespace(1,10,6)
np.random.randint(1,15,[3,4])

array([[ 4, 14, 14,  4],
       [10, 12, 10, 10],
       [ 7,  9,  9,  6]])

In [ ]:
# Ṇutshell 

## we create arrays
# 1. np.array()
# 2. np.ones()
# 3. np.zeros()
# 4. np.arange()
# 5. np.linespace()
# 6. np.random()
# 7. np.random.randint()
## Arrays have some attributes and function 
