In [1]:
# !python -m pip install numpy
!pip install numpy  

     ---------------------------------------- 0.0/14.8 MB ? eta -:--:--
     ---------------------------------------- 0.1/14.8 MB 1.3 MB/s eta 0:00:12
     ---------------------------------------- 0.1/14.8 MB 2.2 MB/s eta 0:00:07
     ---------------------------------------- 0.1/14.8 MB 2.2 MB/s eta 0:00:07
     ---------------------------------------- 0.1/14.8 MB 2.2 MB/s eta 0:00:07
     ---------------------------------------- 0.1/14.8 MB 2.2 MB/s eta 0:00:07
     --------------------------------------- 0.2/14.8 MB 583.1 kB/s eta 0:00:26
      -------------------------------------- 0.3/14.8 MB 749.3 kB/s eta 0:00:20
     - -------------------------------------- 0.4/14.8 MB 1.1 MB/s eta 0:00:13
     - -------------------------------------- 0.6/14.8 MB 1.4 MB/s eta 0:00:11
     -- ------------------------------------- 0.8/14.8 MB 1.6 MB/s eta 0:00:09
     -- ------------------------------------- 0.9/14.8 MB 1.6 MB/s eta 0:00:09
     -- ------------------------------------- 1.0/14.8 MB

In [2]:
!pip install pandas

     ---------------------------------------- 0.0/11.2 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.2 MB 1.4 MB/s eta 0:00:09
     ---------------------------------------- 0.1/11.2 MB 1.1 MB/s eta 0:00:11
      --------------------------------------- 0.2/11.2 MB 1.1 MB/s eta 0:00:10
      --------------------------------------- 0.2/11.2 MB 1.1 MB/s eta 0:00:10
     - -------------------------------------- 0.3/11.2 MB 1.4 MB/s eta 0:00:09
     - -------------------------------------- 0.4/11.2 MB 1.5 MB/s eta 0:00:08
     - -------------------------------------- 0.4/11.2 MB 1.5 MB/s eta 0:00:08
     -- ------------------------------------- 0.6/11.2 MB 1.5 MB/s eta 0:00:07
     -- ------------------------------------- 0.8/11.2 MB 1.6 MB/s eta 0:00:07
     --- ------------------------------------ 0.9/11.2 MB 1.7 MB/s eta 0:00:07
     --- ------------------------------------ 0.9/11.2 MB 1.7 MB/s eta 0:00:07
     --- ------------------------------------ 1.1/11.2 MB 1

In [1]:
# Working With Python Modules


In [2]:
import numpy

In [3]:
numpy.version.version 

'1.24.2'

In [2]:
import keyword

In [4]:
keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [7]:
# here i want to write command in short than i can use "as" it give me to keep short name of function  
import keyword as kw
kw.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [8]:
from keyword import kwlist, iskeyword as isk
kwlist


['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [9]:
isk('if')

True

In [1]:
import numpy as np

In [2]:
a = np.array([]) # empty data set
a
# it create an empty araay 
# array([], dtype=float64) 

array([], dtype=float64)

In [6]:
b = np.array([3,4,5,6,7])
b

array([3, 4, 5, 6, 7])

In [7]:
len(a)

0

In [8]:
len(a),len(b)

(0, 5)

In [9]:
# ATTRIBUTE THAT HELPFUL IN NUMPPY

# a.dtype
# b.dtype
# b.shape
# b.size
# a.shape
# a.ndim
# b.ndim


In [10]:
# CREATING A 2-D ARRAY 

c = np.array([[1,3,4], [5,6,7], [7,8,9], [10,11,12]])  # Here it is important that keep in mind that inside the array same length 
c

# sabse bahar vala bracket denote "no of rows"
# jab main bahar vaale bracket se ek ander aya toh  "no of columns" 

array([[ 1,  3,  4],
       [ 5,  6,  7],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
c.shape

# (4, 3) --> 4 rows and 3 column

(4, 3)

In [12]:
# I want to creagte a dimension 4 X 3 X 1
d = np.array([[[1],[3],[4]], [[5],[6],[7]], [[7],[8],[9]], [[10],[11],[12]]]) 
d


# [] sabse bahar vala bracket denote "no of rows"
# [[]]jab main bahar vaale bracket se ek ander aya toh  "no of columns"
# [[[]]] ab 

array([[[ 1],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [13]:
d.shape

(4, 3, 1)

In [14]:
# I want to creagte a dimension 4 X 3 X 2
e = np.array([[[1,2],[3,4],[4,2]], [[5,1],[6,2],[7,9]], [[4,7],[3,8],[5,9]], [[7,10],[8,11],[9,12]]]) 
e

array([[[ 1,  2],
        [ 3,  4],
        [ 4,  2]],

       [[ 5,  1],
        [ 6,  2],
        [ 7,  9]],

       [[ 4,  7],
        [ 3,  8],
        [ 5,  9]],

       [[ 7, 10],
        [ 8, 11],
        [ 9, 12]]])

In [15]:
e.shape

(4, 3, 2)

In [16]:
c.sum(axis=1)

array([ 8, 18, 24, 33])

In [17]:
c.mean(axis=1)

array([ 2.66666667,  6.        ,  8.        , 11.        ])

In [ ]:
# how can i access the from dimension 
# if i want to access more than one element fro matrix than i can use "scripting"

# indexing, slicing, and third one is scpriting 

# c[0][1]
# c[0:2, -1]
# c[0:2, -1:]
