In [1]:
# Ṇutshell 

## we create arrays
# 1. np.array()
# 2. np.ones()
# 3. np.zeros()
# 4. np.arange()
# 5. np.linespace()
# 6. np.random()
# 7. np.random.randint()
## Arrays have some attributes and function 


In [2]:
import numpy as np

In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
np.arange(1,11,1) #kaha se chalna hai kaha tak jana hai usse ek kam aur kitne step se chalna hai 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
# np.linspace(1,10,10)
np.linspace(1,10,10, dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
list(range(1,11,1))

# range and arange dono main fark ye hia ki jab range function lagate hai toh iske ander always integer value hi kaam karega isliye agar hame lagta hai ki hme float value ki use karnah hai tab arange 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [17]:
np.random.randint(1,6,1)
# it generates srandom integer isme 'kaha se kaha tak aur kitne'

array([5])

In [18]:
np.random.randint(1,6,[4,3,2])

array([[[2, 3],
        [2, 1],
        [1, 5]],

       [[2, 3],
        [1, 3],
        [3, 4]],

       [[2, 3],
        [1, 2],
        [1, 2]],

       [[2, 3],
        [2, 2],
        [4, 3]]])

In [20]:
np.random.randint(1,600,[4,3])

array([[545, 169, 332],
       [188, 131, 595],
       [392, 340, 147],
       [576, 356, 345]])

In [26]:
# to stablish the randomness  or to fix the random 
np.random.seed(50)
np.random.randint(10,600,[4,3])


array([[490, 119, 299],
       [142,  80, 239],
       [ 80, 288, 143],
       [268, 105, 260]])

In [27]:
np.random.rand(3,4) 
# it creates random number in between 0 to 1


array([[0.76053669, 0.31000935, 0.3465412 , 0.35176482],
       [0.14546686, 0.97266468, 0.90917844, 0.5599571 ],
       [0.31359075, 0.88820004, 0.67457307, 0.39108745]])

In [30]:
r = np.loadtxt('somedata.txt', dtype=str)
r

array(['Hi', 'this', 'is', 'a', 'file', 'outside', 'python.'], dtype='<U7')

In [35]:
r = np.loadtxt('moredata.txt')
r

array([[ 45.,  34.,  56.,  78.],
       [ 79.,  80., 104.,  33.]])

In [3]:
p = np.random.rand(3,4)
p

array([[0.76624252, 0.33899412, 0.56090745, 0.45234496],
       [0.24449567, 0.21550878, 0.04689678, 0.1171032 ],
       [0.78610675, 0.56375488, 0.43771222, 0.35528377]])

In [10]:
np.savetxt('new-0.txt', p , delimiter=' ')


In [11]:
np.savetxt('new-1.txt', p , delimiter=',')